

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/sistema">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$_SESSION['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">

					</div>

				</div>
			</div>

		</div>
	
		<div class="col-md-6">
				<h3> cursos</h3>


				<?php foreach ($this->view->cursos as $id_curso => $curso) { ?>
					
				
				<div class="row tweet">
				<div class="col">
					<p> <strong> <?=$curso['nome']?>  </strong> 
					</p>
					<br />
					<form action="/cursoCadastro" method="post">
						<input type="hidden" name="action" value="editar">
						<input type="hidden" name="codigo" value="<?=$curso['codigo']?>">
						<input type="hidden" name="nome"   value="<?=$curso['nome']?>">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-warning mb-2"><small>Editar</small></button>
						</div>
						</form>	

						<form action="/cursoCadastro" method="post" >
						<input type="hidden" name="action" value="deletar">
						<input type="hidden" name="codigo" value="<?=$curso['codigo']?>">
						<input type="hidden" name="nome"   value="<?=$curso['nome']?>">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger mb-2"><small>deletar</small></button>
						</div>
					</form>		
				</div>
			</div>

		<?php } ?>
			<form action="/cursoCadastro" method="">
			<button type="submit" class="btn btn-primary mb-2"><small>Cadastrar</small></button>
		</form>


		</div>


	</div>
</div>