<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/logo.png" style=" width: 125px;height: 125px;" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cadastre o curso </h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/cadastrarCurso" method="post">
              <div class="form-group">
                <input type="text"    name = "nome" class="form-control" placeholder="Nome do curso ">
              </div>
              
              <div class="form-group">
                <input type="text"   name = "codigo" class="form-control" placeholder="codigo do curso">
              </div>

              
              <button type="submit" class="btn btn-primary btn-block">Cadastre</button>

             <?php if($this->view->erroCadastroC ){ ?> 

                <small class="form-text  text-danger"> * Erro ao tentar realizar  o cadastro, verifique se os campos foram preenchidos corretamente. </small>


             <?php } ?> 

             
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  