<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/sistema">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$_SESSION['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
		
		<!--	<div class="row mb-2">
				<div class="col tweetBox">
					 <form>
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form> 


				</div>
			</div> -->

		
				<div class="row tweet">
				<div class="col">
					<p><strong>Cursos</strong> </p>

					<br />
					<form action="/curso">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-primary mb-2"><small>Entrar</small></button>
						</div>
					</form>		
				</div>
			</div>


				<div class="row tweet">
				<div class="col">
					<p><strong>Aluno</strong> </p>

					<br />
					<form action="/aluno" >
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-primary mb-2"><small>Entrar</small></button>
						</div>
					</form>		
				</div>
			</div>


				<div class="row tweet">
				<div class="col">
					<p><strong>Importar arquivo XML</strong> </p>

					<br />
					<form action="/importarxml">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-primary mb-2"><small>Importar</small></button>
						</div>
					</form>		
				</div>
			</div>



		</div>


	</div>
</div>